#Main service defaults
DEFAULT_SERVICE_NAME = "Thermiurge Service"
DEFAULT_SERVICE_PORT = 80377

#ThIP header codes
THIP_SEPARATOR = '||-EEEE-||'
THIP_REQUEST_SERVICE_NAME = 1
THIP_NOTIFY_SERVICE_NAME = 2
